on: 
  push:
  pull_request:
  schedule: [cron: "40 6 10 1/2 *"]

name: Tests

jobs:
  fast-test:
    name: fast (${{ matrix.rust }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Build
        run: make build
      - name: Test Fast Tier
        env:
          FULL_APP_TAG: synthetic
        run: make test

  slow-test:
    name: slow (stable)
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build
        run: make build
      - name: Test Full Suite
        run: make test
